name: material_hero_example
description: Container transform animation, based upon local_hero
version: 0.1.0
homepage: https://github.com/muhleder/material_hero
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  material_hero:
    path: ../